version: "3.9"

services:
  front:
    image: sermalenk/skypro-front:lesson-34
    ports:
     - 8080:80
    depends_on:
      - api
  api:
    build:
      context: .
    depends_on:
      postgres:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
    volumes:
      - ./.docker_env:/app/,env
  migrations:
    build:
      context: .
    depends_on:


  pg:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hbpdfy1999
      POSTGRES_DB: diplom_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5