version: "3.9"

services:
  front:
    image: sermalenk/skypro-front:lesson-34
    ports:
      - 8000:80
    depends_on:
      - api
  api:
    image: rizv4n/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    depends_on:
      postgres2:
        condition: "service_healthy"
      migrations:
        condition: "service_completed_successfully"
    volumes:
      - ./.docker_env:/code/.default_env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
  migrations:
    image: rizv4n/todolist:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    depends_on:
      postgres2:
        condition: "service_healthy"
    volumes:
      - ./.docker_env:/code/.default_env
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 30s
      timeout: 5s
      retries: 5
    command: [ "sh", "-c", "sleep 5 && python manage.py migrate" ]
  postgres2:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: postgres
      HOST: postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data